{
 "title": "Kusama  Polkadot",
 "description": "Grafana dashboard for polkadot node metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Node memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "polkadot_memory_usage_bytes" }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "polkadot_cpu_usage_percentage", "legendFormat": "Node CPU Usage Percentage" }
   ]
  },
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "polkadot_block_height_number", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Networking bytes per second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 8 },
   "targets": [
    { "expr": "polkadot_network_per_sec_bytes", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "polkadot_ready_transactions_number",
     "legendFormat": "Number of transactions in the ready queue"
    }
   ]
  },
  {
   "title": "Number of network gossip peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "polkadot_sync_peers", "legendFormat": "Number of network gossip peers" }
   ]
  }
 ]
}